FROM python:3.8

WORKDIR /app

COPY . .

ARG TWILIO_AUTH_TOKEN
ARG AIRTABLE_TOKEN

ARG ZEET_APP
ARG AIRTABLE_API
ARG TWILIO_SENDER_PHONE
ARG GIT_COMMIT_SHA
ARG ZEET_PROJECT
ARG SUPABASE_ANON
ARG STRIPE_WEBHOOK_SECRET
ARG SENDINBLUE_API
ARG TWILIO_ACCOUNT_SID
ARG UVICORN_HOST
ARG ZEET_ENVIRONMENT
ARG GUNICORN_CMD_ARGS
ARG PYTHONUNBUFFERED

RUN apt-get update 
RUN apt-get -y install cron
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

CMD python3 main.py

EXPOSE 7070/tcp